### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by ShadySQL** [toniblyx/security_monkey_cloudformation#5]
Don't have much experience with security monkey but there is an exception when I launched the stack:

Error loading resource from API. Error: <HTTP 502: <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.4.6 (Ubuntu)</center> </body> </html> >

![screen shot 2016-12-30 at 7 41 17 pm](https://cloud.githubusercontent.com/assets/7299059/21568734/94b541bc-cebf-11e6-859a-2ba8422a8cc7.png)

**Comment by toniblyx** [comment]
I understand you have found how to fix it, would you mind to share it please?

**Comment by abu1993** [comment]
please  help
ubuntu@####:/usr/local/src/security_monkey/security_monkey$ sudo python manage.py create_user abumgx@gmail.com Admin
2017-04-28 11:45:53,208 INFO: Started thread pool with 25 core threads and 30 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
Traceback (most recent call last):
  File "manage.py", line 629, in <module>
    main()
  File "manage.py", line 625, in main
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "manage.py", line 207, in create_user
    if users.count() == 0:
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2573, in count
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2379, in scalar
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2348, in one
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2391, in __iter__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2404, in _execute_and_instances
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2395, in _connection_from_session
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 843, in connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 847, in _connection_for_bind
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 315, in _connection_for_bind
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1698, in contextual_connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 324, in connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 608, in _checkout
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 425, in checkout
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 928, in _do_get
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 277, in _create_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 396, in __init__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 509, in __connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/strategies.py", line 95, in connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 185, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/strategies.py", line 89, in connect
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 366, in connect
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
 None None

**Comment by toniblyx** [comment]
It is related to the database configuration, I'll try to reproduce it by myself and fix it.

**Comment by abu1993** [comment]
Please let me know once updates are done

kindest regards
Abulele Mgxabayi
